version: "3.7"
services:
  infra-{{ServiceName}}:
    image: infra-{{ServiceName}}:${IMAGE_VERSION}
    container_name: infra-{{ServiceName}}
    command: python /app/server.py --conf=/app/config/{{ServiceName}}.json
    ports:
      - {{ServicePort}}:{{ServicePort}}
    restart: always
    env_file:
      - ./.env.local
      - ./.env.secret
      - ./.env.shared
    environment:
      TZ: Asia/Shanghai
      DEPLOY_ENV: prod
      LOG_LEVEL: debug
      LOG_PRINTER: disk
      LOG_PRINTER_FILENAME: /app/logs/infra-{{ServiceName}}.log
      LOGURU_SERIALIZE: "false"
    volumes:
      - ~/.infra-config/{{ServiceName}}:/app/config
      - ./.logs:/app/logs
      - ./.persistent:/app/persistent
      - ./.locks:/app/locks
      - ./.shares:/app/shares
    # healthcheck:
    #   test: ["CMD-SHELL", "grpcurl ... || exit 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 30
